
services:
  postgres:
    restart: "always"
    container_name: "auth-service"
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: books_auth
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    volumes:
      - ./pg:/var/lib/postgresql/data/pgdata